[project]
name = "gerber2nc"
version = "0.1.0"
description = "A Python script to make g-code tool paths from Gerber files for milling out simple PCBs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["shapely>=2.1.1"]
